CREATE SEQUENCE SEQ_TBL_SUBMIT_QUEUE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_AUDITLOG
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_BENEFIT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_BRD
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_BRDCTS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_BRDCTSCOMMENT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_BRDCTSLOG
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_CHECKUP
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_CHECKUPCANDIDATE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_COUNSEL
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_ERRORLOG
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_FILEDOWNLOG
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_FILEITEM
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_FUNERAL
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_FUNERALEXPENSE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_FUNERALEXTARGET
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_INVITE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_INVITE_APPLY
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_JPTHERAPY
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_LOGINLOG
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_MEDICALOVER
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_MEDICALOVER_APPLY
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_MEDICALRECEIPT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_MEDICALSUB
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_MEMBERCHANGEHIS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_MEMBERCHANGEHIS_GROUP
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_MEMBERCONTACT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_MENULOG
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_MINUS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_PRIVACYLOG
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_QNA
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_REVERSEVISIT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_REVERSEVISIT_APPLY
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_SCHEDULE01
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_SCHEDULE02
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_SCHEDULE03
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_SETTLER
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_SETTLERCHANGEHIS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_SETTLERCHANGEHIS_GROUP
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_SETTLERFAMILY
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_SETTLERQNA
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_SMSSENDGROUP
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_SMSSENDTARGET
INCREMENT BY 1
START WITH 1
 CACHE 200;

CREATE SEQUENCE SEQ_T_SMSTEMPLATE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_VISIT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_T_VISITOR
START WITH 1
INCREMENT BY 1;